import { describe, expect, it } from "vitest";
import { createDefaultBookmarkName, formatLoopTime } from "../src/library/bookmark-names";

describe("bookmark names", () => {
  it("creates a deterministic default from the video title and A/B points", () => {
    expect(createDefaultBookmarkName("  Canción de práctica  ", 12.5, 78.25)).toBe(
      "Canción de práctica · 0:12.5–1:18.3"
    );
  });

  it("fits autogenerated names in the editable 80-character field", () => {
    const name = createDefaultBookmarkName(
      "Una canción con un título extremadamente largo ".repeat(4),
      1,
      2
    );
    expect(name.length).toBeLessThanOrEqual(80);
    expect(name).toMatch(/ · 0:01\.0–0:02\.0$/u);
  });

  it("formats minute boundaries", () => {
    expect(formatLoopTime(60)).toBe("1:00.0");
  });
});
